#!/bin/bash -l
#PBS -l walltime=6:00:00,nodes=1:ppn=8,mem=4gb
#PBS -m abe
#PBS -M liux3141@umn.edu

cd ~/code/Python/Correlation/src/py_files
module load python3
source activate pythonEnv
python cav_imseq.py ~/Data/Wei/Dynamics_raw/piv_result_10/20 ~/Data/Wei/Dynamics_raw/cav_result/20 &
python cav_imseq.py ~/Data/Wei/Dynamics_raw/piv_result_10/40 ~/Data/Wei/Dynamics_raw/cav_result/40 &
python cav_imseq.py ~/Data/Wei/Dynamics_raw/piv_result_10/60 ~/Data/Wei/Dynamics_raw/cav_result/60 &
python cav_imseq.py ~/Data/Wei/Dynamics_raw/piv_result_10/80 ~/Data/Wei/Dynamics_raw/cav_result/80 &
python cav_imseq.py ~/Data/Wei/Dynamics_raw/piv_result_10/100 ~/Data/Wei/Dynamics_raw/cav_result/100 &
wait
