#!/bin/bash -l
#PBS -l walltime=3:00:00,nodes=1:ppn=8,mem=3gb
#PBS -m abe
#PBS -M liux3141@umn.edu
cd ~/code/Python/Correlation/src/py_files

module load python3
source activate pythonEnv
python overall_intensity.py ~/Data/08062020/00/8-bit ~/Data/08062020/overall_intensity/00 &
python overall_intensity.py ~/Data/08062020/01/8-bit ~/Data/08062020/overall_intensity/01 &
python overall_intensity.py ~/Data/08062020/02/8-bit ~/Data/08062020/overall_intensity/02 &
python overall_intensity.py ~/Data/08062020/03/8-bit ~/Data/08062020/overall_intensity/03 &
python overall_intensity.py ~/Data/08062020/04/8-bit ~/Data/08062020/overall_intensity/04 &
python overall_intensity.py ~/Data/08062020/05/8-bit ~/Data/08062020/overall_intensity/05 &
python overall_intensity.py ~/Data/08062020/06/8-bit ~/Data/08062020/overall_intensity/06 &
python overall_intensity.py ~/Data/08062020/07/8-bit ~/Data/08062020/overall_intensity/07 &
python overall_intensity.py ~/Data/08062020/08/8-bit ~/Data/08062020/overall_intensity/08 &
python overall_intensity.py ~/Data/08062020/09/8-bit ~/Data/08062020/overall_intensity/09 &
python overall_intensity.py ~/Data/08062020/10/8-bit ~/Data/08062020/overall_intensity/10 &
python overall_intensity.py ~/Data/08062020/11/8-bit ~/Data/08062020/overall_intensity/11 &
python overall_intensity.py ~/Data/08062020/12/8-bit ~/Data/08062020/overall_intensity/12 &
wait