#!/bin/bash -l
#PBS -l walltime=4:00:00,nodes=1:ppn=8,mem=3gb
#PBS -m abe
#PBS -M liux3141@umn.edu
cd ~/code/Python/Correlation/src/py_files

module load python3
source activate pythonEnv
python energy_spectrum.py ~/Data/08062020/piv_step_10/00 ~/Data/08062020/energy_spectrum_10/00 0.8 3.3 &
python energy_spectrum.py ~/Data/08062020/piv_step_10/01 ~/Data/08062020/energy_spectrum_10/01 0.8 3.3 &
python energy_spectrum.py ~/Data/08062020/piv_step_10/02 ~/Data/08062020/energy_spectrum_10/02 0.8 3.3 &
python energy_spectrum.py ~/Data/08062020/piv_step_10/03 ~/Data/08062020/energy_spectrum_10/03 0.8 3.3 &
python energy_spectrum.py ~/Data/08062020/piv_step_10/04 ~/Data/08062020/energy_spectrum_10/04 0.8 3.3 &
python energy_spectrum.py ~/Data/08062020/piv_step_10/05 ~/Data/08062020/energy_spectrum_10/05 0.8 3.3 &
python energy_spectrum.py ~/Data/08062020/piv_step_10/06 ~/Data/08062020/energy_spectrum_10/06 0.8 3.3 &
python energy_spectrum.py ~/Data/08062020/piv_step_10/07 ~/Data/08062020/energy_spectrum_10/07 0.8 3.3 &
python energy_spectrum.py ~/Data/08062020/piv_step_10/08 ~/Data/08062020/energy_spectrum_10/08 0.8 3.3 &
python energy_spectrum.py ~/Data/08062020/piv_step_10/09 ~/Data/08062020/energy_spectrum_10/09 0.8 3.3 &
python energy_spectrum.py ~/Data/08062020/piv_step_10/10 ~/Data/08062020/energy_spectrum_10/10 0.8 3.3 &
python energy_spectrum.py ~/Data/08062020/piv_step_10/11 ~/Data/08062020/energy_spectrum_10/11 0.8 3.3 &
python energy_spectrum.py ~/Data/08062020/piv_step_10/12 ~/Data/08062020/energy_spectrum_10/12 0.8 3.3 &
python energy_spectrum.py ~/Data/08062020/piv_step_10/13 ~/Data/08062020/energy_spectrum_10/13 0.8 3.3 &
python energy_spectrum.py ~/Data/08062020/piv_step_10/14 ~/Data/08062020/energy_spectrum_10/14 0.8 3.3 &
wait