#!/bin/bash -l
#PBS -l walltime=4:00:00,nodes=1:ppn=8,mem=1gb
#PBS -m abe
#PBS -M liux3141@umn.edu

cd ~/code/Python/Correlation/src/py_files
module load python3
source activate pythonEnv
python df2_nobp.py ~/Data/Wei/Dynamics_raw/20 ~/Data/Wei/Dynamics_raw/df2nobp_result/20 &
python df2_nobp.py ~/Data/Wei/Dynamics_raw/40 ~/Data/Wei/Dynamics_raw/df2nobp_result/40 &
python df2_nobp.py ~/Data/Wei/Dynamics_raw/60 ~/Data/Wei/Dynamics_raw/df2nobp_result/60 &
python df2_nobp.py ~/Data/Wei/Dynamics_raw/80 ~/Data/Wei/Dynamics_raw/df2nobp_result/80 &
python df2_nobp.py ~/Data/Wei/Dynamics_raw/100 ~/Data/Wei/Dynamics_raw/df2nobp_result/100 &
wait
