#!/bin/bash -l
#PBS -l walltime=16:00:00,nodes=1:ppn=8,mem=2gb
#PBS -m abe
#PBS -M liux3141@umn.edu

cd ~/code/Python/Correlation/src/py_files
module load python3
source activate pythonEnv
python piv_imseq.py ~/Data/Wei/Dynamics_raw/20 ~/Data/Wei/Dynamics_raw/piv_result/20 50 25 30 &
python piv_imseq.py ~/Data/Wei/Dynamics_raw/40 ~/Data/Wei/Dynamics_raw/piv_result/40 50 25 30 &
python piv_imseq.py ~/Data/Wei/Dynamics_raw/60 ~/Data/Wei/Dynamics_raw/piv_result/60 50 25 30 &
python piv_imseq.py ~/Data/Wei/Dynamics_raw/80 ~/Data/Wei/Dynamics_raw/piv_result/80 50 25 30 &
python piv_imseq.py ~/Data/Wei/Dynamics_raw/100 ~/Data/Wei/Dynamics_raw/piv_result/100 50 25 30 &
wait
