#!/bin/bash -l
#PBS -l walltime=24:00:00,nodes=1:ppn=8,mem=4gb
#PBS -m abe
#PBS -M liux3141@umn.edu

cd ~/code/Python/Correlation/src/py_files
module load python3
source activate pythonEnv
python corr_imseq.py ~/Data/Wei/02042020/20-1 ~/Data/Wei/02042020/cl_result/20-1 10 10 &
python corr_imseq.py ~/Data/Wei/02042020/20-2 ~/Data/Wei/02042020/cl_result/20-2 10 10 &
python corr_imseq.py ~/Data/Wei/02042020/20-3 ~/Data/Wei/02042020/cl_result/20-3 10 10 &
python corr_imseq.py ~/Data/Wei/02042020/40-1 ~/Data/Wei/02042020/cl_result/40-1 10 10 &
python corr_imseq.py ~/Data/Wei/02042020/40-2 ~/Data/Wei/02042020/cl_result/40-2 10 10 &
python corr_imseq.py ~/Data/Wei/02042020/40-3 ~/Data/Wei/02042020/cl_result/40-3 10 10 &
wait
