#!/bin/bash -l
#PBS -l walltime=10:00:00,nodes=1:ppn=8,mem=2gb
#PBS -m abe
#PBS -M liux3141@umn.edu

cd ~/code/Python/generic_proc/py_files
module load python3
source activate pythonEnv
python to_tif.py ~/Data/05282020/00.nd2 &
python to_tif.py ~/Data/05282020/01.nd2 &
python to_tif.py ~/Data/05282020/02.nd2 &
python to_tif.py ~/Data/05282020/03.nd2 &
python to_tif.py ~/Data/05282020/04.nd2 &
wait
