#!/bin/bash -l
#PBS -l walltime=16:00:00,nodes=1:ppn=8,mem=2gb
#PBS -m abe
#PBS -M liux3141@umn.edu

cd ~/code/Python/Correlation/src/py_files
module load python3
source activate pythonEnv
python i_div_autocorr.py ~/Data/Wei/02042020/20-1/bp ~/Data/Wei/02042020/div_result_50/20-1 ~/Data/Wei/02042020/i_div_autocorr/20-1 &
python i_div_autocorr.py ~/Data/Wei/02042020/20-2/bp ~/Data/Wei/02042020/div_result_50/20-2 ~/Data/Wei/02042020/i_div_autocorr/20-2 &
python i_div_autocorr.py ~/Data/Wei/02042020/20-3/bp ~/Data/Wei/02042020/div_result_50/20-3 ~/Data/Wei/02042020/i_div_autocorr/20-3 &
python i_div_autocorr.py ~/Data/Wei/02042020/40-1/bp ~/Data/Wei/02042020/div_result_50/40-1 ~/Data/Wei/02042020/i_div_autocorr/40-1 &
python i_div_autocorr.py ~/Data/Wei/02042020/40-2/bp ~/Data/Wei/02042020/div_result_50/40-2 ~/Data/Wei/02042020/i_div_autocorr/40-2 &
python i_div_autocorr.py ~/Data/Wei/02042020/40-3/bp ~/Data/Wei/02042020/div_result_50/40-3 ~/Data/Wei/02042020/i_div_autocorr/40-3 &
wait
