#!/bin/bash -l
#PBS -l walltime=8:00:00,nodes=1:ppn=8,mem=3gb
#PBS -m abe
#PBS -M liux3141@umn.edu
cd ~/code/Python/Correlation/src/py_files

module load python3
source activate pythonEnv
python energy_order.py ~/Data/06232020/piv_imseq_nosmooth/00 ~/Data/06232020/energy_order_nosmooth/00 0.33 10 &
python energy_order.py ~/Data/06232020/piv_imseq_nosmooth/01 ~/Data/06232020/energy_order_nosmooth/01 0.33 10 &
python energy_order.py ~/Data/06232020/piv_imseq_nosmooth/02 ~/Data/06232020/energy_order_nosmooth/02 0.33 10 &
python energy_order.py ~/Data/06232020/piv_imseq_nosmooth/03 ~/Data/06232020/energy_order_nosmooth/03 0.33 10 &
python energy_order.py ~/Data/06232020/piv_imseq_nosmooth/04 ~/Data/06232020/energy_order_nosmooth/04 0.33 10 &
wait