#!/bin/bash -l
#PBS -l walltime=24:00:00,nodes=1:ppn=8,mem=4gb
#PBS -m abe
#PBS -M liux3141@umn.edu

cd ~/code/Python/Correlation/src/py_files
module load python3
source activate pythonEnv
python div.py ~/Data/Wei/Dynamics_raw/piv_result_10/20 ~/Data/Wei/Dynamics_raw/20  ~/Data/Wei/Dynamics_raw/divergence/20 10 10 &
python div.py ~/Data/Wei/Dynamics_raw/piv_result_10/40 ~/Data/Wei/Dynamics_raw/40  ~/Data/Wei/Dynamics_raw/divergence/40 10 10 &
python div.py ~/Data/Wei/Dynamics_raw/piv_result_10/60 ~/Data/Wei/Dynamics_raw/60  ~/Data/Wei/Dynamics_raw/divergence/60 10 10 &
python div.py ~/Data/Wei/Dynamics_raw/piv_result_10/80 ~/Data/Wei/Dynamics_raw/80  ~/Data/Wei/Dynamics_raw/divergence/80 10 10 &
python div.py ~/Data/Wei/Dynamics_raw/piv_result_10/100 ~/Data/Wei/Dynamics_raw/100  ~/Data/Wei/Dynamics_raw/divergence/100 10 10 &
wait
