#!/bin/bash -l
#PBS -l walltime=3:00:00,nodes=1:ppn=8,mem=2gb
#PBS -m abe
#PBS -M liux3141@umn.edu

cd ~/code/Python/Correlation/src/py_files
module load python3
source activate pythonEnv
python df2_nobp.py ~/Data/Wei/02182020/vid/No.1P_static/16-bit ~/Data/Wei/02182020/vid/df2nobp_result_16bit/No.1P_static
python df2_nobp.py ~/Data/Wei/02182020/vid/No.1P_dynamic/16-bit ~/Data/Wei/02182020/vid/df2nobp_result_16bit/No.1P_dynamic
wait
