#!/bin/bash -l
#PBS -l walltime=24:00:00,nodes=1:ppn=8,mem=4gb
#PBS -m abe
#PBS -M liux3141@umn.edu

cd ~/code/Python/Correlation/src/py_files
module load python3
source activate pythonEnv
python df_imseq.py ~/Data/Wei/02042020/60-1 ~/Data/Wei/02042020/df_result/60-1 &
python df_imseq.py ~/Data/Wei/02042020/60-2 ~/Data/Wei/02042020/df_result/60-2 &
python df_imseq.py ~/Data/Wei/02042020/60-3 ~/Data/Wei/02042020/df_result/60-3 &
python df_imseq.py ~/Data/Wei/02042020/80-1 ~/Data/Wei/02042020/df_result/80-1 &
python df_imseq.py ~/Data/Wei/02042020/80-2 ~/Data/Wei/02042020/df_result/80-2 &
python df_imseq.py ~/Data/Wei/02042020/80-3 ~/Data/Wei/02042020/df_result/80-3 &
wait
