#!/bin/bash -l
#PBS -l walltime=20:00:00,nodes=1:ppn=8,mem=3gb
#PBS -m abe
#PBS -M liux3141@umn.edu
cd ~/code/Python/PIV/src/py_files

module load python3
source activate pythonEnv
python piv_imseq.py ~/Data/12092020/00/8-bit ~/Data/12092020/piv_step_50/00 100 50 1 1 1 &
python piv_imseq.py ~/Data/12092020/01/8-bit ~/Data/12092020/piv_step_50/01 100 50 1 1 1 &
python piv_imseq.py ~/Data/12092020/02/8-bit ~/Data/12092020/piv_step_50/02 100 50 1 1 1 &
wait