#!/bin/bash -l
#PBS -l walltime=24:00:00,nodes=1:ppn=8,mem=4gb
#PBS -m abe
#PBS -M liux3141@umn.edu

cd ~/code/Python/Correlation/src/py_files
module load python3
source activate pythonEnv
python df2_nobp.py ~/Data/Wei/02042020/60-1/16-bit ~/Data/Wei/02042020/df2nobp_result/60-1 &
python df2_nobp.py ~/Data/Wei/02042020/60-2/16-bit ~/Data/Wei/02042020/df2nobp_result/60-2 &
python df2_nobp.py ~/Data/Wei/02042020/60-3/16-bit ~/Data/Wei/02042020/df2nobp_result/60-3 &
python df2_nobp.py ~/Data/Wei/02042020/80-1/16-bit ~/Data/Wei/02042020/df2nobp_result/80-1 &
python df2_nobp.py ~/Data/Wei/02042020/80-2/16-bit ~/Data/Wei/02042020/df2nobp_result/80-2 &
python df2_nobp.py ~/Data/Wei/02042020/80-3/16-bit ~/Data/Wei/02042020/df2nobp_result/80-3 &
wait
